name: wvems_protocols
description: Western Virginia EMS Council's Protocols App

publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  date_time_format: ^2.0.1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  freezed: ^0.14.5
  gap: 2.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  implicitly_animated_reorderable_list: ^0.4.1
  json_annotation: ^4.1.0
  material_floating_search_bar: ^0.3.4
  path_provider: ^2.0.5
  screenshot: ^1.0.0-nullsafety.1
  share_plus: ^2.1.4
  validators2: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/quick-reference/
                                              