name: wvems_protocols
description: Western Virginia EMS Council's Protocols App

publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^6.0.0
  flutter_pdfview: ^1.1.0
  freezed: ^0.14.1+1
  gap: 2.0.0-nullsafety.1
  get: ^4.1.1
  get_storage: ^2.0.3
  google_fonts: ^2.0.0
  http: ^0.13.1
  implicitly_animated_reorderable_list: ^0.4.0-dev+4
  json_annotation: ^4.0.0
  material_floating_search_bar: ^0.3.3
  mdi: ^5.0.0-nullsafety.0
  path_provider: ^2.0.1
  screenshot: ^1.0.0-nullsafety.1
  share_plus: ^2.1.2
  validators2: ^3.0.0

dev_dependencies:
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  freezed_annotation: ^0.14.1
  json_serializable: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/2021-WVEMS-Protocols/
                                              